version: "3.9"

services:
  server:
    image: server:latest
    ports:
      - "8080:8080"
    depends_on:
      - local_stack
    networks:
      - localhost

  local_stack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    networks:
      - localhost

networks:
  localhost:


